var srcIndex = new Map(JSON.parse('[\
["axum_auth",["",[],["main.rs"]]],\
["axum_desktop",["",[],["lib.rs"]]],\
["axum_hello_world",["",[],["main.rs"]]],\
["axum_router",["",[],["main.rs"]]],\
["dioxus",["",[],["launch.rs","lib.rs"]]],\
["dioxus_autofmt",["",[],["buffer.rs","collect_macros.rs","component.rs","element.rs","expr.rs","indent.rs","lib.rs","writer.rs"]]],\
["dioxus_check",["",[],["check.rs","issues.rs","lib.rs","metadata.rs"]]],\
["dioxus_cli",["",[["cli",[],["autoformat.rs","build.rs","bundle.rs","cfg.rs","check.rs","clean.rs","config.rs","create.rs","init.rs","mod.rs","serve.rs","translate.rs","version.rs"]],["server",[["desktop",[],["mod.rs"]],["fullstack",[],["mod.rs"]],["web",[],["hot_reload.rs","mod.rs","proxy.rs"]]],["mod.rs","output.rs"]]],["assets.rs","builder.rs","error.rs","lib.rs","logging.rs","tools.rs"]]],\
["dioxus_cli_config",["",[],["bundle.rs","cargo.rs","config.rs","lib.rs"]]],\
["dioxus_config_macro",["",[],["lib.rs"]]],\
["dioxus_core",["",[["diff",[],["component.rs","iterator.rs","mod.rs","node.rs"]]],["any_props.rs","arena.rs","dirty_scope.rs","error_boundary.rs","events.rs","fragment.rs","global_context.rs","lib.rs","mutations.rs","nodes.rs","properties.rs","runtime.rs","scope_arena.rs","scope_context.rs","scopes.rs","tasks.rs","virtual_dom.rs"]]],\
["dioxus_core_macro",["",[["component_body",[],["mod.rs","utils.rs"]],["component_body_deserializers",[],["component.rs","inline_props.rs","mod.rs"]],["props",[],["mod.rs"]]],["lib.rs","utils.rs"]]],\
["dioxus_desktop",["",[],["app.rs","assets.rs","config.rs","desktop_context.rs","edits.rs","element.rs","eval.rs","event_handlers.rs","events.rs","file_upload.rs","hooks.rs","ipc.rs","launch.rs","lib.rs","menubar.rs","protocol.rs","query.rs","shortcut.rs","waker.rs","webview.rs"]]],\
["dioxus_ext",["",[],["lib.rs"]]],\
["dioxus_fullstack",["",[["hooks",[],["mod.rs","server_cached.rs","server_future.rs"]],["html_storage",[],["deserialize.rs","mod.rs","serialize.rs"]]],["config.rs","launch.rs","lib.rs","server_fn.rs"]]],\
["dioxus_hooks",["",[],["dependency.rs","lib.rs","use_callback.rs","use_context.rs","use_coroutine.rs","use_effect.rs","use_future.rs","use_hook_did_run.rs","use_memo.rs","use_on_destroy.rs","use_resource.rs","use_root_context.rs","use_signal.rs"]]],\
["dioxus_hot_reload",["",[],["lib.rs"]]],\
["dioxus_html",["",[["events",[],["animation.rs","clipboard.rs","composition.rs","drag.rs","focus.rs","form.rs","image.rs","keyboard.rs","media.rs","mounted.rs","mouse.rs","pointer.rs","scroll.rs","selection.rs","toggle.rs","touch.rs","transition.rs","wheel.rs"]],["native_bind",[],["mod.rs","native_file_engine.rs"]],["web_sys_bind",[],["events.rs","mod.rs"]]],["elements.rs","eval.rs","events.rs","file_data.rs","geometry.rs","global_attributes.rs","input_data.rs","lib.rs","point_interaction.rs","render_template.rs","transit.rs"]]],\
["dioxus_html_internal_macro",["",[],["lib.rs"]]],\
["dioxus_interpreter_js",["",[],["lib.rs","sledgehammer_bindings.rs","write_native_mutations.rs"]]],\
["dioxus_lib",["",[],["lib.rs"]]],\
["dioxus_liveview",["",[["adapters",[],["axum_adapter.rs","mod.rs"]]],["config.rs","element.rs","eval.rs","events.rs","launch.rs","lib.rs","pool.rs","query.rs"]]],\
["dioxus_mobile",["",[],["lib.rs"]]],\
["dioxus_native_core",["",[["utils",[],["cursor.rs","mod.rs","persistant_iterator.rs"]]],["custom_element.rs","dioxus.rs","layout_attributes.rs","lib.rs","node.rs","node_ref.rs","node_watcher.rs","passes.rs","real_dom.rs","tree.rs"]]],\
["dioxus_native_core_macro",["",[],["lib.rs"]]],\
["dioxus_playwright_fullstack_test",["",[],["main.rs"]]],\
["dioxus_playwright_liveview_test",["",[],["main.rs"]]],\
["dioxus_playwright_web_test",["",[],["main.rs"]]],\
["dioxus_pwa_example",["",[],["main.rs"]]],\
["dioxus_router",["",[["components",[],["default_errors.rs","history_buttons.rs","link.rs","outlet.rs","router.rs"]],["contexts",[],["navigator.rs","outlet.rs","router.rs"]],["history",[],["memory.rs","mod.rs","web.rs","web_history.rs","web_scroll.rs"]],["hooks",[],["use_navigator.rs","use_route.rs","use_router.rs"]],["utils",[],["use_router_internal.rs"]]],["lib.rs","navigation.rs","routable.rs","router_cfg.rs"]]],\
["dioxus_router_macro",["",[],["layout.rs","lib.rs","nest.rs","query.rs","redirect.rs","route.rs","route_tree.rs","segment.rs"]]],\
["dioxus_rsx",["",[["hot_reload",[],["hot_reload_diff.rs","hot_reloading_context.rs","hot_reloading_file_map.rs","mod.rs"]]],["attribute.rs","component.rs","element.rs","errors.rs","ifmt.rs","lib.rs","node.rs"]]],\
["dioxus_server_macro",["",[],["lib.rs"]]],\
["dioxus_signals",["",[["global",[],["memo.rs","mod.rs","signal.rs"]]],["copy_value.rs","impls.rs","lib.rs","map.rs","props.rs","reactive_context.rs","read.rs","read_only_signal.rs","signal.rs","write.rs"]]],\
["dioxus_ssr",["",[],["cache.rs","config.rs","eval.rs","lib.rs","renderer.rs","template.rs"]]],\
["dioxus_tailwind",["",[],["main.rs"]]],\
["dioxus_tui",["",[],["element.rs","events.rs","lib.rs"]]],\
["dioxus_web",["",[],["cfg.rs","dom.rs","eval.rs","event.rs","file_engine.rs","hot_reload.rs","launch.rs","lib.rs","mutations.rs","rehydrate.rs"]]],\
["dx",["",[],["main.rs"]]],\
["generational_box",["",[],["error.rs","lib.rs","references.rs","sync.rs","unsync.rs"]]],\
["plasmo",["",[["widgets",[],["button.rs","checkbox.rs","input.rs","mod.rs","number.rs","password.rs","slider.rs","text_like.rs","textbox.rs"]]],["config.rs","focus.rs","hooks.rs","layout.rs","lib.rs","prevent_default.rs","query.rs","render.rs","style.rs","style_attributes.rs","widget.rs"]]],\
["rsx_rosetta",["",[],["lib.rs"]]],\
["salvo_hello_world",["",[],["main.rs"]]],\
["static_hydrated",["",[],["main.rs"]]],\
["warp_hello_world",["",[],["main.rs"]]]\
]'));
createSrcSidebar();
