[package]
name = "cli-conn-manager"
edition = "2021"
version = "0.4.3"


[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
axum = { version = "0.5.1", features = ["ws"] }
tokio = { version = "1.16.1", features = ["sync", "rt"] }
futures-util = "0.3.11"
